# The settings in this file are very important. You can specify different environments
# such as 'staging' or 'test', however usually only 'production' is needed

base: &base
  domain: getjobsworth.org  # The tenant specific hostname will be prepended to this domain
  productName: Jobsworth
  SSL: false
  store_root: <%= Rails.root.join("store") %>

  # outbound email settings
  email_domain: getjobsworth.org
  replyto: admin
  from: admin
  prefix: "[Jobsworth]"

  smtp:
    address: localhost
    port: 25
    domain: getjobsworth.org

  receiving_emails:
    secret: k4soAd4lqr4Znh_jL7EcaA       # this key protects the API for sending emails into jobsworth

  devise:
    secret_key: 115687a45bc2f5da3579c00917126acc115687a45bc2f5da3579c00917126acc115687a45bc2f5da3579c00917126acc115687a45bc2f5da3579c00917126acc

  # Allow user and company creation?
  contact_creation_allowed: true

production:
  <<: *base

test:
  <<: *base

development:
  <<: *base