common: &common
  receiving_emails:
    secret: k4soAd4lqr4Znh_jL7EcaA       # it's important to use a different key in production environment
    url: http://getjobsworth.org/emails  # change the protocol(https?), host, port to fit your server

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common