development:
  adapter: jdbc
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8

test:
  adapter: jdbc
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8

production:
  adapter: jdbc
  jndi: java:comp/env/jdbc/jobsworth
  encoding: utf8
  pool: 100
